name: Docs

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Test doc examples
        run: cargo test --doc --workspace

      - name: Build docs
        run: >
          RUSTDOCFLAGS="--enable-index-page -Zunstable-options"
          cargo doc --no-deps --workspace

      - name: Setup GitHub Pages
        if: github.event_name == 'push'
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v2
        with:
            path: target/doc

      - name: Deploy
        if: github.event_name == 'push'
        uses: actions/deploy-pages@v2
